version: 1.0.{build}
image:
  - Visual Studio 2019
  - Ubuntu2004
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
    - main
build: off
build_script:
  - pushd src
  - go generate
  - popd
  - pushd out
  - go build .
  - popd
